### ISSUE TITLE
Fijiro/BatterySystemMod combability 

### ISSUE THREAD

**Issue by Birgerev** [space-commits/SPT-Realism-Mod-Server#51]
Hello! I am working on updating [Fijiro/BatterySystemMod](https://github.com/fijiro/BatterySystemMod) to spt 3.9.4 ([Here is my 3.9.4 Version Fork](https://github.com/Birgerev/BatterySystemMod)) and would love to help make these two mods compatible. I know they [used to be in the past(the old compatibility commit)](https://github.com/space-commits/SPT-Realism-Mod-Server/commit/6f82232e78675faba40ba507affc4790e8e633e7#diff-ff76074f225c732d9285a77349568bea94eb160b1f381004e3435ff940eefa92R384), but looking in to RealismMod code it seems this combability has since been stripped...

Would love to know where you stand on this and if there's anything I can do to help @space-commits!

**Comment by Birgerev** [comment]
Also saw that this was commented out in mod.checkForMods():
```
// if (modname.includes("Jiro-BatterySystem")) {
//     ModTracker.batteryModPresent = true;
//     logger.logWithColor("Realism: Jiro Battery Mod Detected, Making Adjustments", LogTextColor.GREEN);
// }
```

**Comment by space-commits** [comment]
There were bugs and a lot has changed as far as SPT bot gen. If you can figure out a competent way to add compatibility without bugs/issues I'd be willing to add your PR.

**Comment by Birgerev** [comment]
Alright I'll see what I can do. Thanks for the reply!
