### ISSUE TITLE
Compatibility issue with Fika Dedicated plugin

### ISSUE THREAD

**Issue by psalad** [space-commits/SPT-Realism-Mod-Server#52]
Hi, this not an issue with the mod in its intended configuration as it typically works flawlessly,

However, when being used with the new experimental fika dedicated client, the mod uses the auto-generated "fika-dedicated" profile in its calculation for the average level of players connected to the server. Given that this profile is level 1 (or 0 im not sure?), the average level is significantly decreased, causing lower-level bots than expected to spawn in raid.

This happens as long as the dedicated client is connected, regardless of whether its being used to host the raid.

As I mentioned, the mod works perfectly for me in its intended setup, so more of a compatibility issue with the design of the new fika dedicated plugin using a "real" client and profile. so just a heads up more than anything.

Thanks for your amazing work so far.

**Comment by space-commits** [comment]
Thanks but I don't think there's much of anything I can do about that on my side, maybe you can manually edit the level assigned to the dedicated host if it has a profile
