### ISSUE TITLE
mk4a_plate and xsapi_chest Item have no TemplateId and cause a format issue when load mag preset

### ISSUE THREAD

**Issue by OutsiderH** [space-commits/SPT-Realism-Mod-Server#60]
![Desktop Screenshot 2024 10 02 - 17 24 56 13](https://github.com/user-attachments/assets/5b4a0799-9e45-4a81-9057-20d651101e0d)
![Desktop Screenshot 2024 10 02 - 17 25 08 59](https://github.com/user-attachments/assets/4148f0cf-93ae-4ddc-97c9-76f161f9ed30)

**Comment by space-commits** [comment]
They do have a template ID, you even it in the first screenshot. What you're getting at is that they do not have a valid MongoID, as most custom items from SPT mods don't as it didn't used to cause issues in the past till BSG started checking for valid MongoIDs. This is a known issue that will be resolved once all mods, including this one, switch to MongoIDs.
