### ISSUE TITLE
Utils.saveToJSONFile appears to try to write to the wrong path

### ISSUE THREAD

**Issue by DrakiaXYZ** [space-commits/SPT-Realism-Mod-Server#8]
The method "saveToJSONFile" in src/utils.ts appears to be trying to get the mod path by splitting up the current file path, and grabbing 3 parts of it.

It's hard to tell exactly why this is failing, but on some users systems this results in an invalid path being used for updating the config.json file when Realism needs to write out an update. 

Perhaps it's a CWD issue, where if you run from a shortcut it ends up with a bunk path?

**Comment by space-commits** [comment]
Thank you, the issue has been resolved with the latest commit.
