### ISSUE TITLE
Horizontal movements are not counted when shooting from the hip (RM Test 22)

### ISSUE THREAD

**Issue by MrFlashMode** [space-commits/SPT-Realism-Mod-Server#9]
At least it happens before we fire a couple of aiming shots (when we press RMB)

To reproduce the problem does not "special" even need anything:

1) Start the game.
2) Go to the firing range in a hideout or load in any raid.
3) Start shooting from the hipfire

Video Demonstration (if needed) - https://youtu.be/mgipZCxQMFs

**Comment by MrFlashMode** [comment]
Fixed in latest dev build. Thanks mate

**Comment by space-commits** [comment]
next time please write issues for the correct repo, this is the server repo not client.
